// ============================================================
// js/70n-sicily.ts — events for Sicilian Solfifera Series
// ============================================================
// Cianciana / Caltanissetta district, Agrigento province, Sicily.
// Messinian (6-5.3 Ma) sedimentary native-sulfur deposit hosted in
// the Solfifera Series — the gypsum+marl sequence laid down during
// the Mediterranean salinity crisis. The world's primary sulfur
// production center 1860s-1950s; the canonical sedimentary BSR
// native-sulfur deposit type.
//
// Mechanism (Ziegenbalg et al. 2010 Sedimentary Geology; Manzi
// et al. 2009 Sedimentary Geology; Decima & Wezel 1971):
//   1. Messinian gypsum (CaSO₄·2H₂O) precipitated in the Sicilian
//      basin during the 6-5.3 Ma salinity crisis.
//   2. Anaerobic bacterial sulfate reduction (BSR) at depth used
//      the gypsum sulfate as electron acceptor:
//        CaSO₄ + 2 CH₂O (organic-C) → CaS + 2 H₂CO₃
//      H₂S accumulates in the gypsum-marl horizon. Some BSR-mediated
//      microorganisms also directly precipitate S° in the basin
//      sediment (the bacterial-disproportionation pathway).
//   3. The modeled pore inherits elemental sulfur produced by the
//      anaerobic microbial community over geological time. Molecular
//      O₂ is not required for this Sicilian pathway (Rouwendaal et al. 2025).
//   5. Co-products: calcite cement (from CaCO₃ generated by step 2),
//      residual gypsum (selenite), celestine where Sr is available.
//
// Engine fit (SIM 243): native sulfur consumes only the explicit S°
// reservoir. The Sicilian pathway is selected independently of Sulphur
// Bank's oxidative interface and remains anoxic throughout the run.
//
// 4 handlers — gypsum dissolution, microbial sulfate reduction,
// carbonate buffering, and inherited elemental-sulfur recharge.

function event_sicily_gypsum_dissolution(c) {
  // Meteoric water dissolves the encasing Messinian gypsum
  // (CaSO₄·2H₂O), releasing Ca²⁺ + SO₄²⁻ into the porewater. SO₄
  // is the upstream substrate that BSR converts to H₂S; we add it
  // into the explicit sulfate reservoir. Mild pH increase from the
  // dissolution (saturating
  // toward 7.5 the calcite-gypsum equilibrium point).
  c.fluid.Ca += 200;
  addSulfurToPool(c.fluid, 'sulfate', 100, c.temperature);
  c.fluid.Sr += 5;             // Messinian gypsum carries 1-3% Sr; celestine signature
  c.fluid.pH = Math.min(6.5, c.fluid.pH + 0.3);
  c.flow_rate = 0.4;
  return `Meteoric water dissolves Messinian gypsum: Ca rises to ${c.fluid.Ca.toFixed(0)} ppm, S to ${c.fluid.S.toFixed(0)} ppm. Sr trace boost for celestine. Carbonate equilibrium pulls pH toward ${c.fluid.pH.toFixed(1)}.`;
}

function event_sicily_bsr_reduction(c) {
  // Anaerobic microbes reduce a measured increment of gypsum-derived
  // sulfate. Organic matter is the declared boundary electron donor.
  const reaction = bacterialReduceSulfate(c.fluid, 25, c.temperature);
  c.fluid.O2 = Math.min(c.fluid.O2, 0.02);
  c.fluid.Eh = ehFromO2(c.fluid.O2);
  c.flow_rate = 0.2;
  return `Anaerobic microbial sulfate reduction transfers ${reaction.sulfurTransferredPpm.toFixed(1)} ppm sulfate-S to reduced S and adds ${reaction.carbonateAddedPpm.toFixed(1)} ppm carbonate-equivalent alkalinity. Sulfur closes at ${reaction.sulfurAfterPpm.toFixed(1)} ppm; O₂ remains anoxic at ${c.fluid.O2.toFixed(2)}.`;
}

function event_sicily_carbonate_buffer(c) {
  // BSR-generated H₂CO₃ + carbonate-buffered porewater stabilizes pH
  // around 6.0 — the peak of the engine's BSR-mode ph_f factor.
  // CO₃ accumulates from BSR's organic-C oxidation; Ca holds steady
  // from gypsum dissolution.
  c.fluid.CO3 += 60;
  c.fluid.pH = 6.0;
  c.flow_rate = 0.2;
  return `BSR-generated H₂CO₃ buffers the porewater. CO₃ rises to ${c.fluid.CO3.toFixed(0)} ppm; pH pinned at 6.0 — the peak of the engine's BSR-mode pH factor. Calcite cement starts to precipitate.`;
}

function event_sicily_inherited_sulfur_recharge(c) {
  // Recharge imports already formed elemental sulfur from the surrounding
  // anoxic, sulfur-bearing carbonate reservoir.
  addSulfurToPool(c.fluid, 'elemental', 80, c.temperature);
  c.fluid.O2 = Math.min(c.fluid.O2, 0.02);
  c.fluid.Eh = ehFromO2(c.fluid.O2);
  c.flow_rate = 0.3;
  return `Anoxic porewater imports 80 ppm-equivalent inherited microbial S° from the surrounding sulfur-bearing carbonate. Elemental S rises to ${c.fluid.S_elemental.toFixed(0)} ppm while dissolved sulfate and sulfide remain separate.`;
}

// Save compatibility for pre-SIM-243 event ids. New scenarios use the names
// above, but an old local save still resolves and receives corrected science.
function event_sicily_meteoric_o2_pulse(c) { return event_sicily_bsr_reduction(c); }
function event_sicily_late_synproportionation(c) { return event_sicily_inherited_sulfur_recharge(c); }
