import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import {
  assertCommissionedEvidenceRuntime,
  assertIndexMatchesDist,
  COMMISSIONED_EVIDENCE_NODE_RUNTIME,
  nodeRuntimeDigest,
  nodeRuntimeIdentity,
  producerContractDigest,
  producerContractFiles,
  runtimeDependencyFiles,
  runtimeExecutionDigest,
} from '../tools/evidence-runtime.mjs';
import { buildFileBundlePrelude } from '../tools/file-bundle-assets.mjs';
import { checkGuidedTutorialBrowserReceipt } from '../tools/check-guided-tutorial-browser-receipt.mjs';
import {
  buildGuidedTutorialBrowserReceipt,
  readGuidedTutorialBrowserReceipt,
} from '../tools/guided-tutorial-browser-receipt.mjs';
import {
  artifactHashMap,
  verifyArtifactHashMap,
} from '../tools/science-evidence-receipt.mjs';
import {
  currentEvidenceIdentity,
  loadAuthenticatedEvidenceJson,
  requireEvidenceScenario,
} from './authenticated-evidence';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

function writeFixtureIndex(root: string, source: string) {
  const header = '// auto-generated by `npm run build` from js/**/*.ts \u2014 edit those files, not this block';
  const body = `${buildFileBundlePrelude(root)}\n\n// \u2500\u2500 00.js \u2500\u2500\n\n${source}`;
  fs.writeFileSync(path.join(root, 'index.html'), [
    '<script>', '// === BUILD:bundle:start ===', header, '', body, '',
    '// === BUILD:bundle:end ===', '</script>', '',
  ].join('\n'));
}

function makeExecutionFixture() {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'vugg-execution-set-'));
  fs.mkdirSync(path.join(root, 'dist'), { recursive: true });
  fs.mkdirSync(path.join(root, 'data'), { recursive: true });
  fs.mkdirSync(path.join(root, 'narratives'), { recursive: true });
  fs.writeFileSync(path.join(root, 'dist', '00.js'), 'const answer = 42;\n');
  for (const name of ['minerals.json', 'thermo-carbonates.json', 'thermo-sulfates.json']) {
    fs.writeFileSync(path.join(root, 'data', name), '{}\n');
  }
  fs.writeFileSync(path.join(root, 'data', 'scenarios.json5'), '{ scenarios: {} }\n');
  fs.writeFileSync(path.join(root, 'narratives', 'quartz.md'), '# Quartz\n');
  writeFixtureIndex(root, 'const answer = 42;');
  return root;
}

describe('evidence executable and producer identities', () => {
  it('declares one install-visible evidence producer formation', () => {
    expect(COMMISSIONED_EVIDENCE_NODE_RUNTIME).toEqual({
      schema: 'vugg-evidence-node-runtime-v1',
      node: '24.15.0',
      v8: '13.6.233.17-node.48',
      platform: 'win32',
      arch: 'x64',
      icu: '78.2',
      locale: 'en-US',
    });
    expect(assertCommissionedEvidenceRuntime()).toBe(true);
    expect(() => assertCommissionedEvidenceRuntime({
      ...COMMISSIONED_EVIDENCE_NODE_RUNTIME,
      node: '22.23.2',
      v8: '12.4.254.21-node.33',
      platform: 'linux',
    })).toThrow('evidence producer runtime is not commissioned');

    const packageJson = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'));
    const packageLock = JSON.parse(fs.readFileSync(path.join(ROOT, 'package-lock.json'), 'utf8'));
    expect(packageJson.engines?.node).toBe(COMMISSIONED_EVIDENCE_NODE_RUNTIME.node);
    expect(packageLock.packages?.['']?.engines?.node)
      .toBe(COMMISSIONED_EVIDENCE_NODE_RUNTIME.node);
    expect(fs.readFileSync(path.join(ROOT, '.node-version'), 'utf8').trim())
      .toBe(COMMISSIONED_EVIDENCE_NODE_RUNTIME.node);
    expect(fs.readFileSync(path.join(ROOT, '.npmrc'), 'utf8'))
      .toContain('engine-strict=true');

    const guardedWriters = [
      'tools/gen-locality-frequency-baseline.mjs',
      'tools/gen-strip-archive.mjs',
      'tools/gen-js-baseline.mjs',
      'tools/gen-strip-digest.mjs',
      'tools/gen-mechanism-witnesses.mjs',
      'tools/review-claim-card.mjs',
      'tools/science-evidence-receipt.mjs',
      'tools/gen-science-provenance-manifest.mjs',
      'tools/release-audit.mjs',
    ];
    for (const relative of guardedWriters) {
      const source = fs.readFileSync(path.join(ROOT, relative), 'utf8');
      expect(source, relative).toContain('assertCommissionedEvidenceRuntime();');
    }
    const browserSource = fs.readFileSync(path.join(ROOT, 'tools/browser-workflow.mjs'), 'utf8');
    expect(browserSource).toContain("if (process.argv.includes('--write-guided-receipt'))");
    expect(browserSource).toContain('assertCommissionedEvidenceRuntime();');

    expect(packageJson.scripts?.['gen:browser-receipt'])
      .toBe('node tools/browser-workflow.mjs --write-guided-receipt');
    expect(packageJson.scripts?.['audit:browser-receipt'])
      .toBe('node tools/check-guided-tutorial-browser-receipt.mjs');
    const workflow = fs.readFileSync(path.join(ROOT, 'tools/science-workflow.mjs'), 'utf8');
    expect(workflow.indexOf("run('guided browser receipt preflight'"))
      .toBeGreaterThan(workflow.indexOf("run('compile and rebuild local game bundle'"));
    expect(workflow.indexOf("run('guided browser receipt preflight'"))
      .toBeLessThan(workflow.indexOf("run('three-seed locality-frequency receipt'"));

    const versionSource = fs.readFileSync(path.join(ROOT, 'js', '15-version.ts'), 'utf8');
    const simVersion = Number(/const SIM_VERSION = (\d+);/.exec(versionSource)?.[1]);
    const published = readGuidedTutorialBrowserReceipt(ROOT, simVersion);
    const current = buildGuidedTutorialBrowserReceipt(
      ROOT,
      simVersion,
      published.payload.journeys,
      published.payload.browser_runtime,
    );
    expect(checkGuidedTutorialBrowserReceipt({ root: ROOT, simVersion, receipt: current }))
      .toBe(true);
    expect(() => checkGuidedTutorialBrowserReceipt({
      root: ROOT, simVersion: simVersion + 1, receipt: current,
    })).toThrow('identity mismatch');
    expect(() => checkGuidedTutorialBrowserReceipt({
      root: ROOT,
      simVersion,
      receipt: { ...current, producer_contract_sha256: '0'.repeat(64) },
    })).toThrow('identity mismatch');
  });

  it('binds the numeric platform and default collation runtime', () => {
    const identity = nodeRuntimeIdentity();
    expect(identity).toEqual({
      schema: 'vugg-evidence-node-runtime-v1',
      node: process.versions.node,
      v8: process.versions.v8,
      platform: process.platform,
      arch: process.arch,
      icu: process.versions.icu || null,
      locale: new Intl.Collator().resolvedOptions().locale,
    });
    expect(nodeRuntimeDigest()).toMatch(/^[0-9a-f]{64}$/);
  });

  it('binds the exact dist executable and fetched scientific data', () => {
    const root = makeExecutionFixture();
    expect(assertIndexMatchesDist(root)).toBe(true);
    const before = runtimeExecutionDigest(root);
    fs.writeFileSync(path.join(root, 'data', 'minerals.json'), '{"changed":true}\n');
    expect(() => runtimeExecutionDigest(root)).toThrow('index.html does not contain the exact dist');
    writeFixtureIndex(root, 'const answer = 42;');
    expect(runtimeExecutionDigest(root)).not.toBe(before);
    fs.writeFileSync(path.join(root, 'dist', '00.js'), 'const answer = 43;\n');
    expect(() => runtimeExecutionDigest(root)).toThrow('index.html does not contain the exact dist');
  });

  it('canonicalizes checkout newlines without weakening executable or producer identity', () => {
    const lf = makeExecutionFixture();
    const crlf = makeExecutionFixture();
    for (const file of runtimeDependencyFiles(crlf)) {
      const text = fs.readFileSync(file, 'utf8').replace(/\r?\n/g, '\r\n');
      fs.writeFileSync(file, text);
    }
    writeFixtureIndex(crlf, 'const answer = 42;');
    expect(runtimeExecutionDigest(crlf)).toBe(runtimeExecutionDigest(lf));

    const producerRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'vugg-producer-eol-'));
    for (const source of producerContractFiles(ROOT, 'mechanism-witnesses')) {
      const relative = path.relative(ROOT, source);
      const destination = path.join(producerRoot, relative);
      fs.mkdirSync(path.dirname(destination), { recursive: true });
      fs.writeFileSync(destination,
        fs.readFileSync(source, 'utf8').replace(/\r?\n/g, '\r\n'));
    }
    expect(producerContractDigest(producerRoot, 'mechanism-witnesses'))
      .toBe(producerContractDigest(ROOT, 'mechanism-witnesses'));
  });

  it('invalidates every harness-using producer when harness semantics change', () => {
    for (const kind of [
      'seed42-baseline', 'strip-archive', 'locality-frequency', 'strip-digest',
      'claim-cards', 'science-provenance', 'science-receipt',
    ]) {
      const root = fs.mkdtempSync(path.join(os.tmpdir(), `vugg-producer-${kind}-`));
      const sourceFiles = producerContractFiles(ROOT, kind);
      for (const source of sourceFiles) {
        const relative = path.relative(ROOT, source);
        const destination = path.join(root, relative);
        fs.mkdirSync(path.dirname(destination), { recursive: true });
        fs.copyFileSync(source, destination);
      }
      const before = producerContractDigest(root, kind);
      fs.appendFileSync(path.join(root, 'tools', '_harness.mjs'), '\n// changed harness\n');
      expect(producerContractDigest(root, kind), kind).not.toBe(before);
    }
  });

  it('discovers transitive local producer imports instead of relying on a hand list', () => {
    const files = producerContractFiles(ROOT, 'locality-frequency')
      .map(file => path.relative(ROOT, file).replaceAll('\\', '/'));
    expect(files).toContain('tools/locality-frequency-checkpoint.mjs');
    expect(files).toContain('tools/scenario-evidence-checkpoint.mjs');
    expect(files).toContain('tools/evidence-runtime.mjs');
    expect(files).toContain('tools/_harness.mjs');
    expect(files).toContain('package-lock.json');
  });

  it('fails a clean-checkout aggregate receipt when a published artifact changes', () => {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), 'vugg-published-evidence-'));
    const artifact = path.join(root, 'archive', 'story.json');
    fs.mkdirSync(path.dirname(artifact), { recursive: true });
    fs.writeFileSync(artifact, '{"state":42}\n');
    const hashes = artifactHashMap(root, [artifact]);
    expect(verifyArtifactHashMap(root, hashes)).toBe(true);
    fs.writeFileSync(artifact, '{"state":43}\n');
    expect(() => verifyArtifactHashMap(root, hashes)).toThrow('artifact hash mismatch');
  });

  it('gates test evidence through the current aggregate receipt and fails closed', () => {
    const evidence = loadAuthenticatedEvidenceJson(
      `tests-js/baselines/seed42_v${currentEvidenceIdentity.simVersion}.json`,
      'seed42-baseline',
    );
    expect(requireEvidenceScenario(evidence, 'supergene_oxidation')).toBeTruthy();
    expect(() => requireEvidenceScenario(evidence, 'not_an_authored_scenario'))
      .toThrow('no scenario row');
    expect(() => loadAuthenticatedEvidenceJson('../package.json', 'seed42-baseline'))
      .toThrow('escapes repository');
  });
});
