import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import {
  buildFileBundlePrelude,
  canonicalText,
  canonicalTextBytes,
  fileBundleAssetFiles,
} from './file-bundle-assets.mjs';

const START_MARKER = '// === BUILD:bundle:start ===';
const END_MARKER = '// === BUILD:bundle:end ===';

export const EVIDENCE_EXECUTION_SCHEMA = 'vugg-evidence-execution-set-v2';
export const EVIDENCE_PRODUCER_SCHEMA = 'vugg-evidence-producer-contract-v3';
export const EVIDENCE_NODE_RUNTIME_SCHEMA = 'vugg-evidence-node-runtime-v1';

export function nodeRuntimeIdentity() {
  return {
    schema: EVIDENCE_NODE_RUNTIME_SCHEMA,
    node: process.versions.node,
    v8: process.versions.v8,
    platform: process.platform,
    arch: process.arch,
    icu: process.versions.icu || null,
    locale: new Intl.Collator().resolvedOptions().locale,
  };
}

export function nodeRuntimeDigest() {
  return crypto.createHash('sha256')
    .update(JSON.stringify(nodeRuntimeIdentity())).digest('hex');
}

function walkFiles(directory, accept) {
  const out = [];
  const visit = (current) => {
    for (const entry of fs.readdirSync(current, { withFileTypes: true })) {
      const absolute = path.join(current, entry.name);
      if (entry.isDirectory()) visit(absolute);
      else if (entry.isFile() && accept(entry.name, absolute)) out.push(absolute);
    }
  };
  visit(directory);
  return out.sort((a, b) => a.localeCompare(b));
}

export function distModuleFiles(root) {
  const dist = path.join(root, 'dist');
  return walkFiles(dist, name => !name.startsWith('.') && name.endsWith('.js'));
}

function concatDistModules(root) {
  const dist = path.join(root, 'dist');
  return distModuleFiles(root).map((file) => {
    const relative = path.relative(dist, file).replaceAll('\\', '/');
    return `// \u2500\u2500 ${relative} \u2500\u2500\n\n${canonicalText(fs.readFileSync(file, 'utf8')).replace(/\s+$/, '')}`;
  }).join('\n\n');
}

function indexExecutableBody(root) {
  return `${buildFileBundlePrelude(root)}\n\n${concatDistModules(root)}`;
}

export function assertIndexMatchesDist(root) {
  const indexPath = path.join(root, 'index.html');
  const html = fs.readFileSync(indexPath, 'utf8');
  if (html !== canonicalText(html)) {
    throw new Error('evidence runtime mismatch: index.html is not canonical LF text');
  }
  const start = html.indexOf(START_MARKER);
  const end = html.indexOf(END_MARKER);
  if (start < 0 || end < 0 || end <= start) throw new Error('index.html build markers are missing or malformed');
  const startLineEnd = html.indexOf('\n', start);
  const endLineStart = html.lastIndexOf('\n', end) + 1;
  const newline = '\n';
  const body = canonicalText(indexExecutableBody(root));
  const expected = '// auto-generated by `npm run build` from js/**/*.ts \u2014 edit those files, not this block'
    + newline + newline + body + newline + newline;
  const actual = html.slice(startLineEnd + 1, endLineStart);
  if (actual !== expected) {
    throw new Error('evidence runtime mismatch: index.html does not contain the exact dist executable');
  }
  return true;
}

function hashFileSet(root, schema, files) {
  const hash = crypto.createHash('sha256');
  hash.update(`${schema}\0`);
  for (const file of files) {
    const relative = path.relative(root, file).replaceAll('\\', '/');
    hash.update(`${relative.length}:${relative}\0`);
    const bytes = canonicalTextBytes(fs.readFileSync(file));
    hash.update(`${bytes.length}:`);
    hash.update(bytes);
    hash.update('\0');
  }
  return hash.digest('hex');
}

export function browserBundleDigest(root) {
  assertIndexMatchesDist(root);
  return crypto.createHash('sha256').update(fs.readFileSync(path.join(root, 'index.html'))).digest('hex');
}

export function runtimeDependencyFiles(root) {
  const runtimeAssets = fileBundleAssetFiles(root).map(relative => path.join(root, relative));
  const files = [...distModuleFiles(root), ...runtimeAssets];
  for (const file of files) {
    if (!fs.existsSync(file)) throw new Error(`evidence runtime dependency is missing: ${path.relative(root, file)}`);
  }
  return files.sort((a, b) => a.localeCompare(b));
}

export function runtimeExecutionDigest(root) {
  assertIndexMatchesDist(root);
  return hashFileSet(root, EVIDENCE_EXECUTION_SCHEMA, runtimeDependencyFiles(root));
}

const PRODUCER_ENTRIES = Object.freeze({
  'seed42-baseline': ['tools/gen-js-baseline.mjs'],
  'strip-archive': ['tools/gen-strip-archive.mjs'],
  'locality-frequency': ['tools/gen-locality-frequency-baseline.mjs'],
  'strip-digest': ['tools/gen-strip-digest.mjs'],
  'mechanism-witnesses': ['tools/gen-mechanism-witnesses.mjs'],
  'guided-tutorial-browser': [
    'tools/browser-workflow.mjs',
    'tools/guided-tutorial-browser-receipt.mjs',
  ],
  // review-claim-card loads _harness through a computed file URL, which a
  // static import-closure walker cannot discover.
  'claim-cards': ['tools/review-claim-card.mjs', 'tools/_harness.mjs'],
  'science-provenance': ['tools/gen-science-provenance-manifest.mjs'],
  'science-receipt': ['tools/science-evidence-receipt.mjs'],
  'scenario-authoring': ['tools/scenario-authoring.mjs'],
  'release-audit': ['tools/release-audit.mjs'],
  'local-diagnostics': ['tools/local-diagnostics.mjs'],
});

function localImportSpecifiers(source) {
  const matches = [];
  const pattern = /\bfrom\s+['"](\.[^'"]+)['"]|\bimport\s*\(\s*['"](\.[^'"]+)['"]\s*\)/g;
  for (const match of source.matchAll(pattern)) matches.push(match[1] || match[2]);
  return matches;
}

function localImportClosure(entries) {
  const found = new Set();
  const pending = [...entries];
  while (pending.length) {
    const file = path.resolve(pending.pop());
    if (found.has(file)) continue;
    if (!fs.existsSync(file)) throw new Error(`evidence producer file is missing: ${file}`);
    found.add(file);
    const source = fs.readFileSync(file, 'utf8');
    for (const specifier of localImportSpecifiers(source)) {
      const imported = path.resolve(path.dirname(file), specifier);
      if (!found.has(imported)) pending.push(imported);
    }
  }
  return [...found];
}

export function producerContractFiles(root, kind) {
  const entries = PRODUCER_ENTRIES[kind];
  if (!entries) throw new Error(`unknown evidence producer kind: ${kind}`);
  const files = [
    ...localImportClosure(entries.map(relative => path.join(root, relative))),
    path.join(root, 'package-lock.json'),
  ];
  for (const file of files) {
    if (!fs.existsSync(file)) throw new Error(`evidence producer file is missing: ${path.relative(root, file)}`);
  }
  return files.sort((a, b) => a.localeCompare(b));
}

export function producerContractDigest(root, kind) {
  return hashFileSet(root, `${EVIDENCE_PRODUCER_SCHEMA}:${kind}`, producerContractFiles(root, kind));
}
